# Generated by Django 4.2.6 on 2023-10-13 20:16

from django.db import migrations

import prefix_id.field


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    prefix_id.field.PrefixIDField(
                        editable=False,
                        max_length=33,
                        prefix="test_model",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "id_no_prefix",
                    prefix_id.field.PrefixIDField(editable=False, max_length=22, prefix=None, unique=True),
                ),
            ],
        ),
    ]
